config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  resources :exercise_types

  resources :steps

  resources :kilocals
  resources :weights
  resources :exercises

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @weight = Weight.weight
    @steps = Step.step
    @kilocals = Kilocal.kilocal
    @net = Kilocal.kilocal - (Step.step/25) - Exercise.burned
    @exercise = Exercise.exercise
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_form.html.erb
<%= form_for(@dashboard) do |f| %>
  <% if @dashboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dashboard.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% @dashboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :kilocal %><br>
    <%= f.number_field :kilocal %>
  </div>
  <div class="field">
    <%= f.label :exercise_type %><br>
    <%= f.number_field :exercise_type %>
  </div>
  <div class="field">
    <%= f.label :exercise %><br>
    <%= f.number_field :exercise %>
  </div>
  <div class="field">
    <%= f.label :step %><br>
    <%= f.number_field :step %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dashboard/index.html.erb
<div>
<p id="notice"><%= notice %></p>

<h1>Welcome to the Health Tracker!</h1>
<h2>Follow your health by actively recording your calories consumed, steps taken, exercises performed and your weight.</h2>

<br>
<!-- <p> Enter your weight:  <%= @weight %>lbs.</p>
<p> Enter your steps for today: <%= @steps %> </p>
<p> Calories consumed today: <%= @calories_consumed %> calories </p>
<p> Exercises done today: <%= @exercise %></p> -->

<h3>Stats for <%= DateTime.now.month %>/<%= DateTime.now.day %>/<%= DateTime.now.year %>:</h3>
<p> You are <span><%= @weight %></span> lbs.</p>
<p> You have taken <span><%= @steps %></span> steps.</p>
<p> You have consumed <span><%= @kilocals %></span> calories today. </p>
<p> Your net calories for the day: <span><%= @net %></span> </p>
<p> You have done the following exercises today: </p>
<p><span><%= @exercise %></span></p>
<%= link_to 'Log your progress!', new_exercise_path %>
<%= link_to 'Steps taken', new_step_path %>
<%= link_to 'Stuff you ate', new_kilocal_path %>
<%= link_to 'Admit your weight', new_weight_path %>
</div>