config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  resources :exercise_types

  resources :steps

  resources :kilocals
  resources :weights
  resources :exercises

end

app/models/kilocal.rb
class Kilocal < ActiveRecord::Base
  extend Everyday

  validates :number, presence: true

  def self.kilocal
    if Kilocal.where(['created_at > ?', DateTime.now.beginning_of_day]).exists?
      @kilocals = Kilocal.where(['created_at > ?', DateTime.now.beginning_of_day]).sum(:number)
    else
      @kilocals = 0
    end
  end

end

app/controllers/kilocals_controller.rb
class KilocalsController < ApplicationController
  before_action :set_kilocals, only: [:show, :edit, :update, :destroy]
  def index
    @kilocals = Kilocal.all
  end
  def show
    @kilocals = Kilocal.find(params[:id])
  end

  def new
    @kilocals = Kilocal.new
  end

  def edit
  end

  def create
    @kilocals = Kilocal.new(kilocal_params)

    respond_to do |format|
      if @kilocals.save
        format.html { redirect_to kilocals_url, notice: 'Cals were successfully recorded.' }
        format.json { render :index, status: :created, location: @kilocals}
      else
        format.html { render :new }
        format.json { render json: @kilocals.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @kilocals.update(kilocal_params)
        format.html { redirect_to kilocals_url, notice: 'Cals were successfully updated.' }
        format.json { render :index, status: :ok, location: @kilocals }
      else
        format.html { render :edit }
        format.json { render json: @kilocals.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @kilocals.destroy
    respond_to do |format|
      format.html { redirect_to kilocals_url, notice: 'Cals were successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_kilocals
    @kilocals = Kilocal.find(params[:id])
  end

  def kilocal_params
    params.require(:kilocal).permit(:number, :meal_type)
  end
end

app/helpers/kilocal_helper.rb
module KilocalHelper
end

app/views/kilocals/_form.html.erb
<%= form_for(@kilocals) do |f| %>
  <% if @kilocals.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kilocals.errors.count, "error") %> prohibited this kilocals from being saved:</h2>

      <ul>
      <% @exercise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="select">
    <%= f.select(:meal_type, options_for_select([["Breakfast", "Breakfast"], ["Brunch", "Brunch"], ["Lunch", "Lunch"], ["Dinner", "Dinner"], ["Brinner", "Brinner"],["Snack", "Snack"]], :selected => 'lies')) %>
  </div>

  <div class="field">
    <%= f.label :number_of_kilocals %><br>
    <%= f.text_field :number %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kilocals/index.html.erb
<div>
<p id="notice"><%= notice %></p>

<h1>Kilocals</h1>

<table align="center">
  <thead>
    <tr>
      <th>Calories consumed</th>
      <th>Date consumed</th>
      <th>Meal type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kilocals.each do |kilocal| %>
      <tr>
        <td><%= kilocal.number%></td>
        <td><%= kilocal.created_at.in_time_zone('Eastern Time (US & Canada)')%></td>
        <td><%= kilocal.meal_type%></td>
        <td><%= link_to 'Show', kilocal %></td>
        <td><%= link_to 'Edit', edit_kilocal_path(kilocal) %></td>
        <td><%= link_to 'Destroy', kilocal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<p>Most recent entry:</p>
<p><%= Kilocal.everyday %></p>
<%= link_to 'New Kilocals', new_kilocal_path %>
<%= link_to 'Back to dashboard', root_path %>
</div>

app/views/kilocals/new.html.erb
<div>
<h1>Calories</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>
</div>

app/views/kilocals/show.html.erb
<h1>Kilocal#show</h1>
<p>Find me in app/views/kilocal/show.html.erb</p>