config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  resources :exercise_types

  resources :steps

  resources :kilocals
  resources :weights
  resources :exercises

end

app/models/weight.rb
class Weight < ActiveRecord::Base
  extend Everyday
  validate :validate_first_entry_of_the_day
  def self.weight
      Weight.order(created_at: :desc).first.weight if Weight.count>0
  end

  private def validate_first_entry_of_the_day
    errors.add(:weight, "Entry already exists for today") if Weight.where(['created_at > ?', DateTime.now.beginning_of_day]).exists?
  end

end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  before_action :set_weight, only: [:show, :edit, :update, :destroy]

  # GET /weights
  # GET /weights.json
  def index
    @weights = Weight.all
  end

  # GET /weights/1
  # GET /weights/1.json
  def show
  end

  # GET /weights/new
  def new
    @weight = Weight.new
  end

  # GET /weights/1/edit
  def edit
  end

  # POST /weights
  # POST /weights.json
  def create
    @weights = Weight.all
    @weight = Weight.new(weight_params)

    respond_to do |format|
      if @weight.save
          format.html { redirect_to weights_url, notice: 'Weight was successfully created.' }
          format.json { render :index, status: :created, location: @weight }
      else
        format.html { render :new }
        format.json { render json: @weight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weights/1
  # PATCH/PUT /weights/1.json
  def update
    respond_to do |format|
      if @weight.update(weight_params)
        format.html { redirect_to weights_url, notice: 'Weight was successfully updated.' }
        format.json { render :index, status: :ok, location: @weight }
      else
        format.html { render :edit }
        format.json { render json: @weight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weights/1
  # DELETE /weights/1.json
  def destroy
    @weight.destroy
    respond_to do |format|
      format.html { redirect_to weights_url, notice: 'Weight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weight
      @weight = Weight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weight_params
      params.require(:weight).permit(:weight)
    end
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/views/weights/_form.html.erb
<%= form_for(@weight) do |f| %>
  <% if @weight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weight.errors.count, "error") %> prohibited this weight from being saved:</h2>

      <ul>
      <% @weight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weights/edit.html.erb
<h1>Editing Weight</h1>

<%= render 'form' %>

<%= link_to 'Show', @weight %> |
<%= link_to 'Back', weights_path %>

app/views/weights/index.html.erb
<div>
<p id="notice"><%= notice %></p>

<h1>Listing Weights</h1>

<table align="center">
  <thead>
    <tr>
      <th>Weight</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @weights.each do |weight| %>
      <tr>
        <td><%= weight.weight %></td>
        <td><%= link_to 'Show', weight %></td>
        <td><%= link_to 'Edit', edit_weight_path(weight) %></td>
        <td><%= link_to 'Destroy', weight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<p>Most recent entry:</p>
<p><%= Weight.everyday %></p>
<%= link_to 'New Weight', new_weight_path %>
<%= link_to 'Back to dashboard', root_path %>
</div>

app/views/weights/new.html.erb
<div>
<h1>New Weight</h1>

<%= render 'form' %>

<%= link_to 'Back', weights_path %>
</div>

app/views/weights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weight:</strong>
  <%= @weight.weight %>
</p>

<%= link_to 'Edit', edit_weight_path(@weight) %> |
<%= link_to 'Back', weights_path %>