config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  resources :exercise_types

  resources :steps

  resources :kilocals
  resources :weights
  resources :exercises

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]

  # GET /exercises
  # GET /exercises.json
  def index
    @exercises = Exercise.all
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
  @exercise = Exercise.find(params[:id])
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created.' }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: 'Exercise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_exercise
    @exercise = Exercise.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def exercise_params
    params.require(:exercise).permit(:hours, :number, :exercise_type_id)
  end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_form.html.erb
<%= form_for(@exercise) do |f| %>
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% @exercise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="select">
    <%= f.select(:exercise_type_id, options_for_select([["Shoulders", 1], ["Arms", 2], ["Back", 3], ["Chest", 4], ["Legs", 5],["Abs", 6]], :selected => 'lies')) %>
  </div>



  <div class="field">
    <%= f.label :hours %><br>
    <%= f.text_field :hours %>
  </div>
  <div class="field">
    <%= f.label :calories_burned %><br>
    <%= f.text_field :number %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing Exercise</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercise %> |
<%= link_to 'Back', exercises_path %>

app/views/exercises/index.html.erb
<div>
<p id="notice"><%= notice %></p>

<h1>Listing Exercises</h1>

<table align="center">
  <thead>
    <tr>
      <th>Hours</th>
      <th>Calories burned (per hour)</th>
      <th>Type of workout</th>
      <th>Date Created</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercises.each do |exercise| %>
      <tr>
        <td><%= exercise.hours %></td>
        <td><%= exercise.number %></td>
        <td> <%= exercise.exercise_type.name %></td>
        <td><%= exercise.created_at.in_time_zone('Eastern Time (US & Canada)') %></td>
        <td><%= link_to 'Show', exercise %></td>
        <td><%= link_to 'Edit', edit_exercise_path(exercise) %></td>
        <td><%= link_to 'Destroy', exercise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<p>Most recent entry:</p>
<p><%= Exercise.everyday %></p>
<%= link_to 'New Exercise', new_exercise_path %>
<%= link_to 'Back to dashboard', root_path %>
</div>

app/views/exercises/new.html.erb
<div>
<h1>New Exercise</h1>

<%= render 'form' %>

<%= link_to 'Back', exercises_path %>
</div>

app/views/exercises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hours:</strong>
  <%= @exercise.hours %>
</p>


<p>
  <strong>Calories Burned</strong>
  <%= @exercise.number %>
</p>

<%= link_to 'Edit', edit_exercise_path(@exercise) %> |
<%= link_to 'Back', exercises_path %>